FROM elixir:1.9.0-alpine

ENV HOME=/opt/app

# Install Hex + Rebar
RUN mix do local.hex --force, local.rebar --force

# Cache elixir deps
COPY config/ $HOME/config/
COPY mix.exs mix.lock $HOME/

ENV MIX_ENV=test
RUN mix deps.get --only $MIX_ENV

COPY . $HOME/

# Test
WORKDIR $HOME

CMD mix ecto.setup && mix test
