name: Elixir Tests

on: [push]

jobs:

  build:

    services:
      postgres:
        image: postgres:11
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the test Docker image
      run: docker build . --file Dockerfile.test --tag elixir-tests:$(date +%s)
    - name: Run the test Docker image
      run: docker run elixir-tests:$(date +%s)
      env:
        DATABASE_HOSTNAME: postgres
